"""empty message

Revision ID: 7ef868f209ab
Revises: b4256b9722de
Create Date: 2022-02-28 21:52:21.589990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef868f209ab'
down_revision = 'b4256b9722de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('auth_token', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'auth_token')
    # ### end Alembic commands ###
