"""empty message

Revision ID: a9f79d51b6d5
Revises: 7ef868f209ab
Create Date: 2022-02-28 22:15:48.866602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f79d51b6d5'
down_revision = '7ef868f209ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('provider', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'provider')
    # ### end Alembic commands ###
